### ISSUE TITLE
list the used libraries with its used version and the latest version available

### ISSUE THREAD

**Issue by chae-reliatec** [reliatec-gmbh/LibreClinica#1]
create a list with the used version and the latests version of all the libraries referenced the pom.xml from main, core and web

**Comment by chae-reliatec** [comment]
I created a list with the current used libraries from the pom.xml files of main, core and web.

[Dependencies](../wiki/Dependencies)

**Comment by chae-reliatec** [comment]
I activated the Github [dependency graph](../network/dependencies). The automatic analysis found two security vulnerabilities for the lib _org.keycloak:keycloak-core_  with moderate severity. 

[Keycloak ](https://www.keycloak.org/) is an _Open Source Identity and Access Management_. 
_Fix 1:_
Since I can't find any references for keycloak it should be safe to remove this library. 

_Fix 2:_
The current version used is 3.4.3 and the bugs where fixed in 4.6.0 (latest version is 4.8.3). So changing the version to a at least 4.6.0 should fix these bugs.

**Comment by hkjolhede** [comment]
Hello,
I work at an academic hospital where we have been looking at using OpenClinica for data capture for some of our clinical trials. However, we have been somewhat held back because of the community edition being unmaintained. From what I understand you are looking to develop from the 3.14 branch and updating to newer versions of the dependencies. Perhaps to enable running on Java 9 or 11? Would you be interested in help?

**Comment by chae-reliatec** [comment]
Hello Henrik
You summarized it perfectly and every help is welcome. 
I've seen your commit with the updated jackson version. Since we can't update libraries without documenting it for quality assurance we need some more informations before we can used it (e.g. why it is necessary, how it is tested, ...). We are working on a template for community contributions but this isn't finished yet. I will inform you when it is done.

Regards,
Christian

P.S. I will contact you by email so you will have my contact details.

**Comment by chae-reliatec** [comment]
The dependency list is finished.
