### ISSUE TITLE
add-new-user result in oops

### ISSUE THREAD

**Issue by GerbenRienk** [reliatec-gmbh/LibreClinica#105]
lcw050 tomcat 8.5.50 jvm 1.8.0_231-b11 postgresql 9.5
---

Using the add new user-link in the subject matrix for a study that has **Person ID** as **Not Used**  and also **Collect Subject Date of Birth?** to **Not Used**.

results in the oops-page after submission.
In catalina.out the error is reported as:
javax.persistence.TransactionRequiredException: no transaction is in progress
        at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:398)
        at org.hibernate.internal.SessionImpl.checkTransactionNeededForUpdateOperation(SessionImpl.java:3619)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1474)
 etc.

**Comment by GerbenRienk** [comment]
After updating tomcat and java the error is still there, but only for one study. I can't put my finger on the conditions/differences. 
If it is gone with the next release I'll close the issue.

**Comment by toskrip** [comment]
Is it possible to capture a couple of more line from stacktrace. Above I only see the hibernate calls but I would like to check the method from Dao object from where it originates. I may be able to help with this issue.

**Comment by GerbenRienk** [comment]
I tried it with both v.0.5.0 and v.0.6.0 and attach the relevant log-part in a txt-file
[add_new_subject_logs_20200124.txt](https://github.com/reliatec-gmbh/LibreClinica/files/4109433/add_new_subject_logs_20200124.txt)

**Comment by toskrip** [comment]
ok, and just to clarify. Does the enrollment fail or it the situation that the Opps page is displayed but the patient was actually enrolled into study.

**Comment by GerbenRienk** [comment]
No, no enrollment is takes place.

Op vr 24 jan. 2020 19:39 schreef Tomas Skripcak <notifications@github.com>:

**Comment by toskrip** [comment]
This looks like you try add patient and schedule event. This is triggering rule engine (rule evaluation). The issue in my opinion is in ExpressionService class getStudyEventFromDb method. I think we need to catch TransactionRequiredException and call:

`expressionWrapper.getStudyEventDaoHib().fetchByStudyEventDefOIDAndOrdinal(oid, ordinal, studySubjectId)`

when the first transnational call fails (the first one seems to be introduced for participate...). I do not want to start fixing this before I can clearly reproduce it. Do you have steps how to reproduce the issue on testing database (could you edit the first comment with those steps)?

**Comment by toskrip** [comment]
In allowUpdateOutsideTransaction branch the old hibernate behavior was explicitly activated to prevent these type of issues that come form the up versioning of hibernate and will eventually require to refactor the DAO/ Dao layer for proper use of SQL transactions and their propagation.
