### ISSUE TITLE
loading of processAnnotationsJar results in 7 warnings

### ISSUE THREAD

**Issue by GerbenRienk** [reliatec-gmbh/LibreClinica#106]
lcw050 tomcat 8.5.11 jvm 1.8.0_121-b13 postgresql 9.5
---
When starting lcw050 the following error is reported in catalina.out:
11-Jan-2020 14:09:07.835 SEVERE [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.processAnnotationsJar Unable to process Jar entry [module-info.class] from Jar [file:/usr/local/tomcat8/webapps/lcw050/WEB-INF/lib/istack-commons-runtime-3.0.7.jar] for annotations org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19

This happens 7 times, with the following jars:
istack-commons-runtime-3.0.7.jar 
txw2-2.3.1.jar 
jaxb-api-2.3.1.jar
jaxb-runtime-2.3.1.jar 
FastInfoset-1.2.15.jar 
byte-buddy-1.9.10.jar 
stax-ex-1.8.jar

**Comment by chae-reliatec** [comment]
I had a look at this and istack-commons-runtime-3.0.7.jar and FastInfoset-1.2.15.jar require at lease Java 9. The other libs do not explicitly require Java 9 or do require older versions although please try it it Java 9 or newer (Java 13 is the current version).

**Comment by chae-reliatec** [comment]
All these libs are (transitive) requirements of hibernate-core. The hibernate ORM release notes claim that Java 1.8, Java 11 and Java 13 is supported so maybe updating your java version might help (8u121 is from January 2017, 8u231 is from October 2019).

**Comment by GerbenRienk** [comment]
I updated to 8u231, but the same errors occur.
I'm afraid I can't use Java 13, as it is only available for 64-bit os.

**Comment by chae-reliatec** [comment]
There are some good explanations about this issue when you search for the error message.

The key problem is the mixture of Tomcat-8.5.x and Java-1.8. The _module-info.class_ was introduced for Java-9 and therefore can't be read with Java-1.8 and should be ignored. But Tomcat 8.5.x tries to load it even when only Java-1.8 is installed.

I couldn't find if this is changed for newer Tomcat-8.5.x versions but it should be worth a try (8.5.11 is from Janurary 2017, 8.5.50 from December 2019). If this still does not work you should consider to update to Java-9 at least.

**Comment by GerbenRienk** [comment]
The following combination works:
Server version name:   Apache Tomcat/8.5.50
Server built:          Dec 7 2019 19:19:46 UTC
Server version number: 8.5.50.0
OS Name:               Linux
OS Version:            3.2.41-042stab141.3
Architecture:          i386
Java Home:             /opt/jdk1.8.0_231/jre
JVM Version:           1.8.0_231-b11
JVM Vendor:            Oracle Corporation
