### ISSUE TITLE
Creating CRF throws NPE

### ISSUE THREAD

**Issue by medonja** [reliatec-gmbh/LibreClinica#107]
Hi,

I've tried setting up a new CRF and am getting a NPE when using the following CRF spreadsheet:  https://drive.google.com/file/d/1RPCqrpwtrkgEEPdRF4ejlXXiaPimRDR3/view?usp=sharing

However, there is no NPE thrown when I try to import the CRF into a standard OC instance.

Can you help me out with this one?

This appears to be happening on both LC 0.4 and 0.5 releases.

Best,
Marko

**Comment by chae-reliatec** [comment]
Hi Marko

I do assume that as before you've installed LibreClinica in a docker container.

**Comment by medonja** [comment]
Hi,

yes indeed :) Does that somehow change anything? I did install OC as well in a docker container, so I assumed LC would work as well.

Best,
Marko

**Comment by chae-reliatec** [comment]
Unfortunately it makes a difference (although I currently can't explain in detail why) when LC is run in a docker container vs. when it is run in different virtual machine. It might be due to the host OS and its configuration.
We're aware of this issue and it is related to your former issue. We do not run LC in Docker containers and do not have this problem but we'll discuss it's priority in the next call (which is very soon).

If you're interested in details:
The issue was introduced by the Spring migration and is related to the second level cache instantiation. This is the reason why OC 3.14 does not have this issue.

**Comment by medonja** [comment]
Ah, I see. Dammit :)

Ok, thanks for letting me know and good luck with further development and issue solving!

**Comment by toskrip** [comment]
@medonja , we did tried to find a workaround for proper cache instantiation (seem to be timing problem). Should be fixed in lc-0.7.1 pre-release. If you find time, you could test it with docker and let us know.

**Comment by medonja** [comment]
Hi toskrip, the last days were quite busy and your message slipped somehow through, sorry about that. I will try to find the time until the end of the week and will let you know. Cheers!

**Comment by medonja** [comment]
Hi toskrip, I just saw that you released v1.0.0 of LibreClinica! Kudos for that!
Now, I wanted to try it out, but it seems that the war file is missing from the v1.0.0 release. The previous releases had all a war file attached. Would it be possible to add the war file as well to the latest release?

Thank you and best,
Marko

**Comment by chae-reliatec** [comment]
Hi Marko
The *.war is available now. We had some network issues and therefore had some trouble to upload the archive and I forgot to upload it later.

So thank you for making me aware of this.

Regards,
Christian

**Comment by medonja** [comment]
I can confirm: Importing a CRF worked well! Also, it seems that there are no issues that are similar to those I have previously reported appearing. And I really like the blue LibreClinica color scheme Well done guys! :)

On a sidenote: I would love to use the LibreClinica-ws / is there a separate war for the webservices available too? How can I install the webservice module?

**Comment by chae-reliatec** [comment]
We do not officially provide the war for the webservices since we did not have the resources to test it properly. However you can generate an archive on your own from the sources. If you need help with this, just send us a note.

**Comment by medonja** [comment]
Hi Christian, I would gladly accept your help with building the WS war :)

**Comment by chae-reliatec** [comment]
The war will be published on the LibreClinica homepage with the next release (1.1).
