### ISSUE TITLE
wrong success message for 'RemoveStudyUserRole'

### ISSUE THREAD

**Issue by chae-reliatec** [reliatec-gmbh/LibreClinica#114]
when a user with study role 'Data Manager' is removed the success message is:
>>>
user t010_01(user name: user_t010_01) has been removed from the Study/Site Libre Clinica Test Study with role coordinator. The user will no longer have access to the Study. 
>>>
Instead of 'coordinator' the correct role 'Data Manager' should be shown.

The issue can be reproduced by following the instructions of T010_03

**Comment by toskrip** [comment]
This is because it uses the database name for the role rather then internationalised labels (site_Study_Coordinator, Study_Coordinator) from term.properties.

**Comment by toskrip** [comment]
The same on restore. There it influences not just alert message but also the view.
