### ISSUE TITLE
Wrong remove row icon in eCRF with repeating group

### ISSUE THREAD

**Issue by toskrip** [reliatec-gmbh/LibreClinica#115]
Seems that styling issue was introduced. When eCRF with repeating group is loaded for display the remove row icon is shown only as a rectangle without "X".

![remove-row-icon](https://user-images.githubusercontent.com/786181/72993042-00ec7600-3df5-11ea-8b27-f7d8d41d60d7.png)

**Comment by GerbenRienk** [comment]
this is class button_remove
background-image: url(../images/bt_Remove.gif);

**Comment by chae-reliatec** [comment]
Is fixe in v0.8.1
