### ISSUE TITLE
change question-mark-link to oc-docs

### ISSUE THREAD

**Issue by GerbenRienk** [reliatec-gmbh/LibreClinica#125]
All references to docs.openclinica.com should be removed or replaced, specifically the ones that use bt_Help_Manage.gif, which are hard-coded.
Same for **Help** link in the footer and \include\sideIconsSubject.jsp **View All Icons**

admin\listuseraccounts.jsp
admin\studyAuditLog.jsp
admin\viewAllJobs.jsp
admin\viewCRF.jsp
admin\viewFullStudy.jsp
admin\viewImportJobs.jsp
admin\viewJobs.jsp
admin\viewSingleJob.jsp
extract\applyFilter.jsp
extract\createDatasetBegin.jsp
extract\createDatasetStep2.jsp
extract\createDatasetStep3.jsp
extract\createDatasetStep4.jsp
extract\createFilterScreen1.jsp
extract\createFilterScreen2.jsp
extract\createFilterScreen3.jsp
extract\createFilterScreen3_1.jsp
extract\createFilterScreen3_2.jsp
extract\createFilterScreen4.jsp
extract\createFilterScreen5.jsp
extract\editDataset.jsp
extract\exportDatasets.jsp
extract\extractDatasetsMain.jsp
extract\generatedDatasetHtml.jsp
extract\generateMetadataFile.jsp
extract\viewDatasets.jsp
extract\viewSelected.jsp
extract\viewSelectedHtml.jsp
login\changeStudy.jsp
login\requestStudy.jsp
login\updateProfile.jsp
managestudy\chooseCRFVersion.jsp
managestudy\confirmCRFVersionChange.jsp
managestudy\createSubjectGroupClass.jsp
managestudy\createSubStudy.jsp
managestudy\findSubjects.jsp
managestudy\index.jsp
managestudy\listStudySubject.jsp
managestudy\listSubjectDiscNote.jsp
managestudy\listUserInStudy.jsp
managestudy\managestudy_body.jsp
managestudy\siteList.jsp
managestudy\studyEventDefinitionList.jsp
managestudy\studyList.jsp
managestudy\studyUserList.jsp
managestudy\subjectGroupClassList.jsp
managestudy\viewNotes.jsp
managestudy\viewNotesPrint.jsp
managestudy\viewStudyEvents.jsp
managestudy\viewStudySubject.jsp
menu.jsp
studymodule.jsp
submit\addExistingSubject.jsp
submit\addNewSubject.jsp
submit\createNewStudyEvent.jsp
submit\discrepancyNote.jsp
submit\enterDataForStudyEvent.jsp
submit\import.jsp
submit\importRules.jsp
submit\index.jsp
submit\instructionsEnrollSubject.jsp
submit\listDNotesForCRF.jsp
submit\listEventsForSubject.jsp
submit\listRuleSets.jsp
submit\listRuleSets2.jsp
submit\listRuleSetsDesigner.jsp
submit\tableOfContents.jsp
submit\verifyImportRule.jsp
techadmin\index.jsp
viewAllSubjectSDVtmp.jsp
viewSubjectAggregate.jsp

**Comment by oba-reliatec** [comment]
Here are my suggestions how to deal with the links to docs.openclinica.com, to be discussed on the next teleconference. libreclinica.org/documentation refers to the page on libreclinica.org where we collect all libreclinica documentation so far available incl. the link to docs.openclinica.com.
https://docs.openclinica.com/3.1/rules
remove
https://docs.openclinica.com/3.1/openclinica-user-guide/...
change to libreclinica.org/documentation
https://docs.openclinica.com/3.1/manage-users/...
remove or change to libreclinica.org/documentation
https://docs.openclinica.com/3.1/administer-crfs-crf-template/...
remove or change to libreclinica.org/documentation
https://docs.openclinica.com/participate/...
remove
https://docs.openclinica.com/randomization/...
dead link anyway
https://www.openclinica.com/OpenClinica/bug.php
dead link anyway

**Comment by toskrip** [comment]
Help icon link will be deactivated and there will be just one reference to LC documentation landing page in footer.
