### ISSUE TITLE
link to ruledesigner results in 404

### ISSUE THREAD

**Issue by GerbenRienk** [reliatec-gmbh/LibreClinica#128]
When in the list of rules you click on the pencil, to start editing the rule with the rule-designer you get a 404. 
Same happens when in Study Build.
For example:
lcw060/oauth/user/authorize?client_id=designer&redirect_uri=http%3A%2F%2Fdesigner13.openclinica.com%2Faccess%3Fhost%3Dhttps%3A%2F%2Ftds-edc.com%26app%3Dlcw060%26target%3DF_LCRULES.IG_LCRUL_UNGROUPED.I_LCRUL_DISCR_BATCH%26ruleOid%3DR_I_LCRUL_DISCR_BATCH_01%26study_oid%3DS_LCTEST%26provider_user%3Dlctest_techadmin%26path%3DViewRuleAssignment%26runTime%3Dnull%26msg%3DDiscrepancy-1-message-1-I_LCRUL_DISCR_BATCH&response_type=code

In datainfo.properties 
**designerURL=https://designer13.openclinica.com/**

**Comment by toskrip** [comment]
Reproduced. 

oauth:authorization-server configuration looks incomplete

/web/src/main/resources/org/akaza/openclinica/applicationContext-security.xml

**Comment by chae-reliatec** [comment]
#188

**Comment by toskrip** [comment]
We should disable the generation of link to Designer as the Designer is currently not working and we are not going to actively maintain Designer anyway.
