### ISSUE TITLE
check if item validator regular expression with \ works after migrating from OC to LC

### ISSUE THREAD

**Issue by chae-reliatec** [reliatec-gmbh/LibreClinica#185]
Create a test where the functionality of an item validator regular expression with \ is checked for an installation that has been migrated from OC to LC.

Details can be found in issue #184.

**Comment by chae-reliatec** [comment]
Restoring the backup of an pg8 database to LC with pg9 worked without any issues. The database is restored as it was and the regexp worked as expected.

**Comment by toskrip** [comment]
Restoring the backup of an pg8 DB to LC with pg11 worked also without any issues.
Restored DB correspond to original DB record and regexp seem to work just fine.
