### ISSUE TITLE
Availability of SOAP and REST APIs and corresponding documentation

### ISSUE THREAD

**Issue by RaviVinnakota** [reliatec-gmbh/LibreClinica#191]
Hi,

Could you please let me know if APIs are available for LibreClinica? If so, could you please point me to the SOAP and REST end point reference/documentation for the same.
Are any specific installation steps required for accessing apis once the LibreClinica is setup as per https://libreclinica.org/documentation/install.html

I posted it here as I could find reference for the same.

Thanks,
Ravi.

**Comment by RaviVinnakota** [comment]
Thanks for your response. So, I understand that the currently supported ones are the ones (All REST APIs) available in https://docs.openclinica.com/3.1/technical-documents/rest-api-specifications and https://dev.openclinica.com/apidoc/ (this link is launched from the earlier link).

**Comment by toskrip** [comment]
supported is a bit strong word, but they should work (if you find otherwise, please let us know). E.g. I was trying RESTful URLs to access metadata and clinical data and those have been fine. Exception would be REST API for rules that require oath authentication endpoint (for this we have an open ticket). The reason why I am not saying officially supported is because we do not have yet functional tests defined for them which also means that we do not test them before release.

**Comment by RaviVinnakota** [comment]
Got it. Thanks. I will surely let you know what all REST APIs are working and the ones that are not, when I test.

**Comment by xryadav** [comment]
Hey Everyone

I’m i the process of testing the APIs on a LibreClinica instance(set up on OpenStack).

I’m following the API documentation of OpenClinica3.1
When i test the http://xx.xx.xxx.xxxx:8080/LibreClinica/pages/accounts/login, the response looks as the following:

{
    "firstName": "ra",
    "lastName": "ya",
    "password": "{7INl76dEQZhjV3/vgNP/Kmru4psSFv8XZzeWMY=}df356ccb4a1d68e2bdedc425824a00043",
    "apiKey": "",
    "roles": [
        {
            "roleName": "coordinator",
            "studyOID": "S_DEFAULTS1"
        }
    ],
    "username": "root"
}

I'm authenticating the api postrequest with basic-auth using username and password. The request return code 200(OK)
The response does not return the api-key. I need the api-key for many other endpoints. Can someone please suggest what might fix my error?
My current setup is:  LibreClinica - 1.1
LibreClinica-ws - 1.1
tomcat - 9.65.0

Thanks
