### ISSUE TITLE
No datainfo.properties file after fresh install

### ISSUE THREAD

**Issue by morksoldat** [reliatec-gmbh/LibreClinica#196]
Hello everybody.

Tried to install LibreClnica following the instructions in https://www.libreclinica.org/documentation/install.html.
On Ubuntu 18.04, openjdk 11.0.8, tomcat 9.0.16, PostgreSQL 10.12.

After flowing the instructions there is no datainfo.properties file, and there is loop in the /config file directory.

```
find -L /usr/share/tomcat9/libreclinica/config/
/usr/share/tomcat9/libreclinica/config/
find: File system loop detected; ‘/usr/share/tomcat9/libreclinica/config/config’ is part of the same file system loop as ‘/usr/share/tomcat9/libreclinica/config/’.
```

service tomcat9 status returns

```
tomcat9.service - Apache Tomcat 9 Web Application Server
   Loaded: loaded (/lib/systemd/system/tomcat9.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-08-11 21:21:54 -04; 23min ago
     Docs: https://tomcat.apache.org/tomcat-9.0-doc/index.html
  Process: 22579 ExecStartPre=/usr/libexec/tomcat9/tomcat-update-policy.sh (code=exited, status=0/SUCCESS)
 Main PID: 22588 (java)
    Tasks: 34 (limit: 2317)
   CGroup: /system.slice/tomcat9.service
           └─22588 /usr/lib/jvm/default-java/bin/java -Djava.util.logging.config.file=/var/lib/tomcat9/conf/logging.properties -Djava.util.logging.man

ago 11 21:22:21 server.virusresp tomcat9[22588]:         at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
ago 11 21:22:21 server.virusresp tomcat9[22588]:         at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:496)
ago 11 21:22:21 server.virusresp tomcat9[22588]: One or more listeners failed to start. Full details will be found in the appropriate container log fi
ago 11 21:22:21 server.virusresp tomcat9[22588]: Falló en arranque del Contexto [/libreclinica] debido a errores previos
ago 11 21:22:22 server.virusresp tomcat9[22588]: Deployment of web application archive [/var/lib/tomcat9/webapps/libreclinica.war] has finished in [23
ago 11 21:22:22 server.virusresp tomcat9[22588]: Desplegando el directorio [/var/lib/tomcat9/webapps/ROOT] de la aplicación web
ago 11 21:22:23 server.virusresp tomcat9[22588]: Al menos un JAR, que se ha explorado buscando TLDs, aún no contenía TLDs. Activar historial de depura
ago 11 21:22:23 server.virusresp tomcat9[22588]: Deployment of web application directory [/var/lib/tomcat9/webapps/ROOT] has finished in [1.591] ms
ago 11 21:22:23 server.virusresp tomcat9[22588]: Starting ProtocolHandler ["http-nio-8080"]
ago 11 21:22:23 server.virusresp tomcat9[22588]: Server startup in [25.667] milliseconds
```

I'm a MD practitioner with basic programing skills so i can't find out whats wrong.

Thanks for making OpenClinica open again!!

**Comment by toskrip** [comment]
From what you describe above, it seems to me that you created a nested soft links on config (config/config). And that loop is the problem. I would remove the config folder that you created and also the soft link and start again according to manual. What you want at beginning is to have new empty folder:

`/usr/share/tomcat9/libreclinica/config`

and then you want to have new soft link that points to that folder (this soft link should be one level uppper in the folder hierarchy, directly under tomcat9):

`/usr/share/tomcat9/libreclinica.config`

LibreClinica will be using that soft link path but the actual datainfo.properties will physically be stored under the config folder (that was created as first). So on first startup LC will create default datainfo.properties file there (which you then need to adapt to your DB connection details).

**Comment by morksoldat** [comment]
Thank for the reply!

cleaned all installs and did all again. Still no datainfo.properties files. Seems loading crash before creating the file.
```
14-Aug-2020 15:28:30.150 INFORMACIÓN [main] org.apache.catalina.startup.HostConfig.deployWAR Despliegue del archivo [/var/lib/tomcat9/webapps/libreclinica.war] de la aplicación web
14-Aug-2020 15:29:00.974 GRAVE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
14-Aug-2020 15:29:00.991 GRAVE [main] org.apache.catalina.core.StandardContext.startInternal Falló en arranque del Contexto [/libreclinica] debido a errores previos
14-Aug-2020 15:29:01.213 INFORMACIÓN [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/var/lib/tomcat9/webapps/libreclinica.war] has finished in [31.062] ms
```
Can't find the "the appropriate container log file" anyware. `/usr/share/tomcat9/libreclinica/logs` is empty.
[catalina.2020-08-14.log](https://github.com/reliatec-gmbh/LibreClinica/files/5076857/catalina.2020-08-14.log)

Full log atached.

**Comment by toskrip** [comment]
and did you resolve your original loop in config directory problem? In another words, can you create manually file via the soft link location,  e.g.:

```
cd /usr/share/tomcat9/libreclinica.config
touch fileWriteTest
```

should create file physically in `/usr/share/tomcat9/libreclinica/config/` directory

**Comment by GerbenRienk** [comment]
Hi both,
For my own installation I also added a softlink to the data-folder:
sudo ln -s /usr/share/tomcat9/libreclinica/data/
/usr/share/tomcat9/libreclinica.data
And don't forget the setup ReadWritePaths plus the reload of the unit-files.
Kind regards,

Gerben Rienk

Op ma 17 aug. 2020 om 17:24 schreef Tomas Skripcak <notifications@github.com

**Comment by morksoldat** [comment]
hi again

I did fix the loop problem, but with the same results. Tried with the softlink to libreclinica.data also. Same result.

Any way to get a more detailed log file from tomcat?

**Comment by chillriver** [comment]
Hell everybocy,

I have the same problem with no datainfo.properties generating after deploying the warfile. Maybe it can't generate because I get everytime the same error in logfile 

`/var/log/tomcat9/catalina.out `

`java.io.FileNotFoundException: /usr/share/tomcat9/logs/libreclinica.2020-11-17.log`

[catalina.out](https://github.com/reliatec-gmbh/LibreClinica/files/5555294/catalina.txt)

I have no such file. Is it wanted like that?

[localhost.log](https://github.com/reliatec-gmbh/LibreClinica/files/5555310/localhost.log)

**Comment by Csucsu1977** [comment]
Hi,
I had the same issue. 
First the file is located here. /var/lib/tomcat9/webapps/libreclinica/WEB-INF/classes
so you have to edit the file at this location, and after first start and successful deployment this file will be moved to the /usr/share/tomcat9/ibreclinica/conf directory

**Comment by Csucsu1977** [comment]
furthermore I had to create the following directories for a successful deployment:
 /usr/share/tomcat9/ibreclinica.data
/usr/share/tomcat9/ibreclinica.data/xslt
all new directories have to be owned by user tomcat!

**Comment by Csucsu1977** [comment]
also in datainfo.proeprties the log dir was changed to 
log.dir=${catalina.home}/libreclinica/logs/

**Comment by chae-reliatec** [comment]
#209

**Comment by chae-reliatec** [comment]
> Hi,
> I had the same issue.
> First the file is located here. /var/lib/tomcat9/webapps/libreclinica/WEB-INF/classes
> so you have to edit the file at this location, and after first start and successful deployment this file will be moved to the /usr/share/tomcat9/ibreclinica/conf directory

That fixes the installation problem. For details have a look at issue #209.

**Comment by chae-reliatec** [comment]
Updated installation instructions.
