### ISSUE TITLE
fix security alert for library keycloak

### ISSUE THREAD

**Issue by chae-reliatec** [reliatec-gmbh/LibreClinica#2]
I activated the Github [dependency graph](../network/dependencies). The automatic analysis found two security vulnerabilities for the lib _org.keycloak:keycloak-core_  with moderate severity. 

[Keycloak ](https://www.keycloak.org/) is an _Open Source Identity and Access Management_. 
_Fix 1:_
Since I can't find any references for keycloak it should be safe to remove this library. 

_Fix 2:_
The current version used is 3.4.3 and the bugs where fixed in 4.6.0 (latest version is 4.8.3). So changing the version to a at least 4.6.0 should fix these bugs.

**Comment by chae-reliatec** [comment]
@toskrip 
As I mentioned I do not find anything where keycloak is actively used. Since it can be run as a standalone server I might be missing the place where it is used.
It seems to me that you once noted keycloak so you might know something that may help to fix this issue.

**Comment by toskrip** [comment]
Keycloak is relevant only for OC4, there is a branch where OC4 uses Keycloak instead of proprietary Auth0 for authentication of all communication within "micro service" architecture.

**Comment by chae-reliatec** [comment]
So it should be safe to remove it?

**Comment by toskrip** [comment]
If we make new master from OC 3.xx branch then yes.

**Comment by chae-reliatec** [comment]
We start with OC-3.14 as the basis for LibreClinica. Did you received the minutes from the last telephone conference?

**Comment by toskrip** [comment]
Yes, I am only mentioning it because I have not seen new lc-master setup yet. The current master already has lots of OC4 stuff in it and piece of code that uses client Keycloak library (although OC4-Keycloak should be the only branch that should use it).

**Comment by chae-reliatec** [comment]
That's exactly the reason for this issue.
I misunderstood the alert and thought that it is related to the 3.14 branch. I will have a look if it is possible to configure the dependency analyzer to ignore the master branch or to use another branch instead (e.g. lc-master). If this is not possible we need to change the naming convention (e.g. oc-master for the original code and master for the LibreClinica code).

**Comment by chae-reliatec** [comment]
Since this issue effects OC-4 only I do close this issue.
