### ISSUE TITLE
Jmesa

### ISSUE THREAD

**Issue by rellai** [reliatec-gmbh/LibreClinica#223]
Good day. Where can I get the sources for jmesa 2.4.2-oc. I would like to migrate changes relative to 2.4.2 to a newer version

**Comment by toskrip** [comment]
Hi, we have been unable to locate public sources (or compiled artifact) for this library. The artifact is still available for download only from OC servers and it may easily be that public sources do not exist. I think the best shot in figuring out changes relative to publicly available jmesa is to decompile it.

**Comment by rellai** [comment]
ok, thnx!
