### ISSUE TITLE
[BUG] ODM export code list element is incomplete

### ISSUE THREAD

**Issue by hillgert** [reliatec-gmbh/LibreClinica#279]
**Description:**

ODM export <CodeList> element does not list all defined entries when empty text entry is selected. This also mesans that it does not correspond to the crf metadata definition.

**Requirements:**

1. A study with some basic configuration to enter data and at least one CRF that contains the following configuration.
1. RESPONSE_OPTIONS_TEXT entry of: ",Komplette Remission,Partielle Remission".
1. RESPONSE_VALUES_OR_CALCULATIONS entry of: "0,1,2".
1. RESPONSE_TYPE entry of: "single-select".
1. DATA_TYPE_ entry of: "INT".
1. RESPONSE_LABEL entry of: "THERAPY".

**Steps to follow:**

1. Login to the system with user with according permissions to upload a crf definition to a study.
1. Upload eCRF definition to the study.
1. Fillout the corresponding configured field and select the pseudo empty (default).
1. Click save
1. Create a dataset with all data points selected.
1. Go through the wizzard and make sure to select _Data from all Available CRFs_.
1. Click _Confirm and Save_.
1. Click _Run Now_ of option _CDISC ODM XML 1.3 Full with OpenClinica extensions_.
1. Click on the link for the export dataset with information e-mail and download zipped export file.
1. Open ODM export file wihtin zipped file.
1. Search for <CodeList> element with name _THERAPY_.

**Expected result:**

1. The <CodeList> element should contain a <CodeListItem> element with according _CodedValue_ of value 0.

**Actual result:**

1. The <CodeList> element does *not* contain a <CodeListItem> element with according _CodedValue_ of value 0.

**Additional context (optional):**

1. Bug is already fixed and a pull request will be started in a timely manner.
2. The made changes are also test-covered.

**Comment by toskrip** [comment]
resolve via merge on lc-develop (resolution of merge conflicts)
