### ISSUE TITLE
log4j should be removed.

### ISSUE THREAD

**Issue by rhe-reliatec** [reliatec-gmbh/LibreClinica#298]
I have looked at the dependencies which infect the project with  log4j.:
![dependencys-33](https://user-images.githubusercontent.com/78546623/146432776-49ca4dfa-fcff-4ecb-981e-9f290e905020.png)

I looked at the source-code of pjl -> commons-logging, poi, jxl and it seems, that they do not really need log4j - in worst case, they do no logging.
If this is true, we may exclude the log4j-dependency.
In LibreClinica there is no need for log4j, there are just some log4j.xml files in the test-folder.
This refers to libreclinica-1.0.

**Comment by toskrip** [comment]
Very good, thanks for initial dependency analysis. We should try to remove this library and see if we can execute all tests without problems.

**Comment by rhe-reliatec** [comment]
I have some automated tests that should do most of the possible clicks on the user interface and simulate the "life of a study". I try these first - if the system passes them, we can be pretty sure that no damage has been done.
These tests only work with libreclinica 1.0. Higher versions seem to break the test environment (i.e. the tests do not work with libreclinica 1.1 and future versions so far). 
... not this year

**Comment by toskrip** [comment]
Ok, the lc-develop branch will be tested with smoke tests. For now I can confirm that by removing the direct dependency and setting up exclusions for pjl, poi and jxl to avoid transient dependencies, log4j will not be packed into the final war archive.
