### ISSUE TITLE
org.openclinica.ns.rules.v31.RunOnScheduleType not exists.

### ISSUE THREAD

**Issue by testingnowdotcom** [reliatec-gmbh/LibreClinica#300]
**Description:**
When i'm importing the propject, i have an issue with class definition that one not exists into project by itself. I mean the path from repository https://github.com/OpenClinica/ocodm/tree/master/src/main/java/org/openclinica/ns/rules/v31, the class i don't find is RunOnScheduleType. Im getting the error into org.openclinica.ns.rules.v31.RuleAssignmentType.java

**Requirements:**
What i did is clone this repository, with "this" i mean https://github.com/reliatec-gmbh/LibreClinica, after clone i make some changes to pom.xml file for mitigate some dependency errors i got before, the dependecy i import is this:

><dependency>
>	<groupId>com.sun.jersey</groupId>
>	<artifactId>jersey-server</artifactId>
>	<version>1.19.4</version>
>	<scope>compile</scope>
></dependency>

**Steps to follow:**
1. Clone repository
2. Changes on pom.xml for mitigate dependency issues.  
2. Add all folders from https://github.com/OpenClinica/ocodm/tree/master/src/main/java/org to this folder https://github.com/reliatec-gmbh/LibreClinica/tree/lc-develop/web/src/main/java/org
3. Generate source and update folders.
4. Reload Project
5. Build project.

**Expected result:**
Having defined the class RunOnScheduleType.

e.g.  
Not getting error by undefined class RunOnScheduleType.

**Actual result:**
Getting error the class isn't defined RunOnScheduleType.

**Screenshots (optional):**
Getting the error explained before.
![170120221149first](https://user-images.githubusercontent.com/97883837/149756244-42e2784c-af59-4a3e-9509-45e26b8d4c48.png)
The class not exists on folder:
![170120221150second](https://user-images.githubusercontent.com/97883837/149756533-ecbc2d2c-8569-4415-8d9d-fad1dda88ad3.png)

**Additional context (optional):**
My intention is build the project and generate a WAR for import into external server with some changes into code base.

**Comment by testingnowdotcom** [comment]
Same issue with NotificationActionType class at ObjectFactory.java and RuleRefType.java, the folder package is the same >org.openclinica.ns.rules.v31

**Comment by testingnowdotcom** [comment]
Ok pressing to maven install magically removes the error. The build is succesful but no stored for some reason in out path. What i want is generate a WAR file for import into server, how can i do it ? The purpose of this is change codebase and can generate a new WAR with added features.

**Comment by testingnowdotcom** [comment]
Configured tomcat server with "Smart Tomcat" plugin because i use Intellij IDEA Community, but im getting the next error when running server:
>org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file. In this case, where is specified "container log file" ? For see the details of error. Another issues i see is on maven compile, how can i fix it ?: 
![170120221644third](https://user-images.githubusercontent.com/97883837/149800188-0f5d07aa-f3a9-4d70-898d-761bde80e327.png)

**Comment by toskrip** [comment]
Those class definitions that do not exist are generated during maven build. The odm module (LibreClinica-odm) is one of dependency for core module. So in short these classes will only exist packed as jar dependency. They are autogenerated from xsd files that are version controlled within odm module.

regarding smart tomcat plugin, cannot be of help here... our developer documentation is currently considering only non community version of intellij that has all features when it comes to java enterprise application development:

https://libreclinica-docs.readthedocs.io/en/latest/dev/dev-machine.html

however you should be able to just use maven on its own:

`mvn clean install -DskipTests`

should crate war packages for deployment in target folder.

**Comment by testingnowdotcom** [comment]
Hi! i'm getting the same 2 errors with dependencies executing the command you wrote:
>mvn clean install -DskipTests
![180120220839first](https://user-images.githubusercontent.com/97883837/149891894-5073066b-23d0-4746-91d4-c5bc19ac4677.png)

When i execute the command i'm getting the next output:

```
"C:\Program Files\Java\jdk1.8.0_202\bin\java.exe" "-Dmaven.multiModuleProjectDirectory=C:\Users\vlady\OneDrive\Documentos\todo lo relacionado con LibreClinica\proyecto libreclinica aqui\LibreClinica" "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1\lib\idea_rt.jar=57974:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2021.3.1 clean install -DskipTests
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] LibreClinica ODM                                                   [jar]
[INFO] LibreClinica                                                       [pom]
[INFO] LibreClinica Core                                                  [jar]
[INFO] LibreClinica Web Application                                       [war]
[INFO] LibreClinica Web Services                                          [war]
[INFO] 
[INFO] ---------------< org.libreclinica.odm:LibreClinica-odm >----------------
[INFO] Building LibreClinica ODM 2.2                                      [1/5]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ LibreClinica-odm ---
[INFO] Deleting C:\Users\vlady\OneDrive\Documentos\todo lo relacionado con LibreClinica\proyecto libreclinica aqui\LibreClinica\odm\target
[INFO] 
[INFO] --- properties-maven-plugin:1.0.0:set-system-properties (set-additional-system-properties) @ LibreClinica-odm ---
[INFO] Set 2 system properties
[INFO] 
[INFO] --- jaxb2-maven-plugin:2.3:xjc (schemas-generate) @ LibreClinica-odm ---
[INFO] Adding 'extension' flag to XJC arguments, since the 'generateEpisode' argument is given. (XJCs 'episode' argument requires that the 'extension' argument is provided).
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ LibreClinica-odm ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\vlady\OneDrive\Documentos\todo lo relacionado con LibreClinica\proyecto libreclinica aqui\LibreClinica\odm\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.1:compile (default-compile) @ LibreClinica-odm ---
[INFO] Compiling 513 source files to C:\Users\vlady\OneDrive\Documentos\todo lo relacionado con LibreClinica\proyecto libreclinica aqui\LibreClinica\odm\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ LibreClinica-odm ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\vlady\OneDrive\Documentos\todo lo relacionado con LibreClinica\proyecto libreclinica aqui\LibreClinica\odm\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.1:testCompile (default-testCompile) @ LibreClinica-odm ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ LibreClinica-odm ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ LibreClinica-odm ---
[INFO] Building jar: C:\Users\vlady\OneDrive\Documentos\todo lo relacionado con LibreClinica\proyecto libreclinica aqui\LibreClinica\odm\target\LibreClinica-odm-2.2.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ LibreClinica-odm ---
[INFO] Installing C:\Users\vlady\OneDrive\Documentos\todo lo relacionado con LibreClinica\proyecto libreclinica aqui\LibreClinica\odm\target\LibreClinica-odm-2.2.jar to C:\Users\vlady\.m2\repository\org\libreclinica\odm\LibreClinica-odm\2.2\LibreClinica-odm-2.2.jar
[INFO] Installing C:\Users\vlady\OneDrive\Documentos\todo lo relacionado con LibreClinica\proyecto libreclinica aqui\LibreClinica\odm\pom.xml to C:\Users\vlady\.m2\repository\org\libreclinica\odm\LibreClinica-odm\2.2\LibreClinica-odm-2.2.pom
[INFO] 
[INFO] -------------------< org.libreclinica:LibreClinica >--------------------
[INFO] Building LibreClinica 1.2.0-snapshot                               [2/5]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ LibreClinica ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ LibreClinica ---
[INFO] Installing C:\Users\vlady\OneDrive\Documentos\todo lo relacionado con LibreClinica\proyecto libreclinica aqui\LibreClinica\pom.xml to C:\Users\vlady\.m2\repository\org\libreclinica\LibreClinica\1.2.0-snapshot\LibreClinica-1.2.0-snapshot.pom
[INFO] 
[INFO] -----------------< org.libreclinica:LibreClinica-core >-----------------
[INFO] Building LibreClinica Core 1.2.0-snapshot                          [3/5]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] LibreClinica ODM 2.2 ............................... SUCCESS [  6.728 s]
[INFO] LibreClinica 1.2.0-snapshot ........................ SUCCESS [  0.076 s]
[INFO] LibreClinica Core 1.2.0-snapshot ................... FAILURE [  0.670 s]
[INFO] LibreClinica Web Application 1.2.0-snapshot ........ SKIPPED
[INFO] LibreClinica Web Services 1.2.0-snapshot ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.593 s
[INFO] Finished at: 2022-01-18T08:35:20+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project LibreClinica-core: Could not resolve dependencies for project org.libreclinica:LibreClinica-core:jar:1.2.0-snapshot: Failed to collect dependencies at org.jmesa:jmesa:jar:2.4.2-oc: Failed to read artifact descriptor for org.jmesa:jmesa:jar:2.4.2-oc: Could not transfer artifact org.jmesa:jmesa:pom:2.4.2-oc from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [jboss-public-repository-group (http://repository.jboss.org/nexus/content/groups/public/, default, releases+snapshots)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :LibreClinica-core

Process finished with exit code 1
``` 

Only seeing the errors, it seems be an issue with dependency no resolving, what repository have this dependencies ?

This issue seems related to https://github.com/OpenClinica/OpenClinica/issues/1203

**Comment by toskrip** [comment]
This dependency is only available from OC server. Make sure that maven can resolve the repository (e.g. if you are behind corporate proxy, make sure that maven can talk outside).

https://openclinica.jfrog.io/artifactory/libs-release/org/jmesa/jmesa/2.4.2-oc/jmesa-2.4.2-oc.jar

your build fails already during resolving dependencies on the core module so naturally target folders have not been generated for web and ws (as you can see from your maven output, build for web and ws was skipped because core failed).

**Comment by testingnowdotcom** [comment]
Hi! is normal if the link you wrote redirects to https://openclinica.jfrog.io/ui/packages ? Or that's caused by network blocking ? I will try with another network. By the case, how can i check if my maven can talk outside ?
