### ISSUE TITLE
[BUG] - Error when filtering subject matrix by study event

### ISSUE THREAD

**Issue by j-bley** [reliatec-gmbh/LibreClinica#316]
**Description:**
An error page is diplayed when filtering subject matrix by study event.

**Requirements:**
LibreClinica version 1.1.0.

Study with at least one study event.

**Steps to follow:**

* Login
* Open Subject matrix
* In drop down list 'Select An Event' choose a random study event

**Expected result:**

The subject matrix filtered by selecet study event is diplayed.

**Actual result:**
Error-page ('Oops! An error has occurred') is dispayed.

**Screenshots:**

![LibreClinica-1-1-0_subject_matrix_filtering](https://user-images.githubusercontent.com/83451119/167135959-1a7f8477-a77d-48ce-b467-f9184a35c76c.png)

![LibreClinica-1-1-0_subject_matrix_filtering_error](https://user-images.githubusercontent.com/83451119/167135956-2f12933e-a921-4798-a21c-6ed85911942f.png)

**Comment by toskrip** [comment]
I can reproduce the problem. I will investigate what is causing the issue.

**Comment by toskrip** [comment]
There is a missing query response type mapping for Study unique_identifier from StudySubject getWithFilterAndSort query when the Event filter is setup in SubjectMatrix. I will prepare the fix for this bug.
