### ISSUE TITLE
2-FA unique account name

### ISSUE THREAD

**Issue by hillgert** [reliatec-gmbh/LibreClinica#349]
**Description:**
Within the pre-release 1.2.2, when scanning a second generated QR Code, this was not possible due to fact that the according authentication app account name was not unique. Creating a new 2-FA account in the app was cumbersome and only possible manually. 

**Requirements:**
- The authentication app account name within the scanned QR code should be unique.

**Expected result:**
- The authentication app account name should provide information about the system.
- Information about the system will get extracted from the sysURL property configuration.
- Therefore the protocol and last URL path shall be removed as it has no relevant information.

**Comment by hillgert** [comment]
Enhancements made within branch "lc-develop-qrcode-additional-info". Request pull request.

**Comment by toskrip** [comment]
I only re-opened the ticket as it gets closed automatically when the pull request is merged (PR and issue are cross-linked now).
