### ISSUE TITLE
Missing API-Key from LibreClinica api test

### ISSUE THREAD

**Issue by xryadav** [reliatec-gmbh/LibreClinica#352]
Hey Everyone

I’m i the process of testing the APIs on a LibreClinica instance(set up on OpenStack).

I’m following the API documentation of OpenClinica3.1
When i test the http://xx.xx.xxx.xxxx:8080/LibreClinica/pages/accounts/login, the response looks as the following:

{
    "firstName": "ra",
    "lastName": "ya",
    "password": "{7INl76dEQZhjV3/vgNP/Kmru4psSFv8XZzeWMY=}df356ccb4a1d68e2bdedc425824a00043",
    "apiKey": "",
    "roles": [
        {
            "roleName": "coordinator",
            "studyOID": "S_DEFAULTS1"
        }
    ],
    "username": "root"
}

I'm authenticating the api postrequest with basic-auth using username and password. The request return code 200(OK)
The response does not return the api-key. I need the api-key for many other endpoints. Can someone please suggest what might fix my error?
My current setup is:  LibreClinica - 1.1
LibreClinica-ws - 1.1
tomcat - 9.65.0

Thanks

**Comment by toskrip** [comment]
By default, when you have a freshly initialised database with default root user the SOAP web services as well as REST services utilising apiKey are disabled for root user (meaning there is no apiKey for that user persisted in database). ApiKey gets generated for every newly created user. For using SOAP as root you need to edit root user and enable the web services flag. When the existing user is edited the apiKey should be re-generated. You can always check in user_account table whether enable_api_key column is true and api_key is set as well as whether run_webservices column that controls the ability to use SOAP is set to true.

**Comment by xryadav** [comment]
Admin apiKey authentication issue:

Thanks a lot for the response it helped me generate the apiKey by enabling the root user settings.
But when I try to test the API endpoints which require admin.apikey for authentication, the http response I'm receiving HTTP code 401(unauthorized). 
 
Example: Retrieve all system module info: http://1x.1xx.1xx.xxx:8080/LibreClinica/MainMenu//10./pages/auth/api/v1/system/modules
I’m passing the apiKey as headers and being a root user, I expect a success but the response is ‘unauthorized’. 
I’m using Postman for testing.
If you happen to know the cause of this error, can you please suggest the correct approach?
 
Regards
Rakesh

**Comment by toskrip** [comment]
personally, I never used those specific endpoints but we I look into the source code, it is protected via ApiSecurityFilter. That filter expect the basic HTTP Authorization header to be set for such request.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

normally this contains from username and password separated with a colon and the resulting string being base64 encoded. I guess postman will do this for you if you configure basic authorization. The username should be set to the value of apiKey and password can be left empty (or any value).

**Comment by toskrip** [comment]
I will close this now as this is not really an issue that we would need to track in ticket system. For further questions please open a discussion in discussions section.
