### ISSUE TITLE
Update Email library

### ISSUE THREAD

**Issue by oba-reliatec** [reliatec-gmbh/LibreClinica#357]
**Description:**
LibreClinica fails to send emails after update to openjdk 11.0.16+

**Requirements:**
A study with some basic configuration enabling to create users.

**Steps to follow:**
1. login
1. create a new user or change password for a user, selecting"Send password to user via email"

**Expected result:**
The email is send, and a message "Your email has been sent successfully" appears

**Actual result:**
The email is not send a message "Mail cannot be sent to the Administrator due to a mail server connection problem." appears.

**Server Setup (optional):**
 - OS Debian 10, Windows 10
 - Java openjdk-11-jdk

**Additional context (optional):**
For further description and solution see the [LibreClinica-Website](https://libreclinica.org/archive/mail_update_warning_20221103.html)

**Comment by oba-reliatec** [comment]
Note that the above mentioned problem could not be reproduced on OS Ubuntu. Here sending emails works with OpenJDK 11.0.**16**+8-post-Ubuntu-0ubuntu120.04 and the old JavaMail mail-1.4.jar.

**Comment by toskrip** [comment]
I would think that it depend how is the JDK distribution configured by default within specific OS, from what I read TLS1.0 and TLS1.1 would normally be disabled now by default in current JDK, but in specific system it may be that TLSv2 is set to be preferred and it does not try 1 or 1.1 anymore (these two would be blocked).
