### ISSUE TITLE
Check for datatype INT isn't working

### ISSUE THREAD

**Issue by GerbenRienk** [reliatec-gmbh/LibreClinica#360]
**Description:**
When you use a field of datatype INT and you enter a character, this is accepted.

**Requirements:**
As form with an item of datatype INT, without further validatiosn, such as range.

**Steps to follow:**
1. login
1. upload attached CRF and assign to it to an event
1. enter the value `A` for the input field
1. click save

**Expected result:**
We expect the error message "[The input you provided is not an integer.]"

**Actual result:**
The form is saved.

**Additional context:**
I could reproduce this in lc 1.1.0, 1.2.0 and 1.2.1

[issue_360.xls](https://github.com/reliatec-gmbh/LibreClinica/files/10361097/issue_360.xls)

**Comment by toskrip** [comment]
Issue reproduced. I will fix that.
