### ISSUE TITLE
is there any plan for a docker image of libreclinica?

### ISSUE THREAD

**Issue by Doutianbao** [reliatec-gmbh/LibreClinica#371]

**Comment by toskrip** [comment]
As the project readme says, currently no official docker image is planned. Unofficially I have seen one image in the dockerhub:

 https://hub.docker.com/r/jaspersnel/libreclinica

I did not tried it myself, that is why I cannot say whether it works fine. I think that in a future it may be that we agree on creating official docker image but right now I cannot promise any specific date of availability.
