### ISSUE TITLE
[BUG] Checkboxes and simple conditional display

### ISSUE THREAD

**Issue by j-bley** [reliatec-gmbh/LibreClinica#381]
**Description:**
After saving a crf with checkboxes which trigger a simple conditional display, the unhidden fields are not visible.

**Requirements:**
CRF with checkboxes and connected simple conditional display.

**Steps to follow:**
1. select checkbox which triggers a simple conditional display
2. do not enter data into undidden fields
3. click save
4. open tab containing checkboxes

**Expected result:**
All fields including unhidden fields should be visible

**Actual result:**
Fields which should be unhidden are hidden and will only be shown when checkbox is deselected and selected

**Comment by toskrip** [comment]
I can confirm that this bug is reproducible.
