### ISSUE TITLE
java: package org.openclinica.ws.crf.v1 does not exist

### ISSUE THREAD

**Issue by faisalshah42** [reliatec-gmbh/LibreClinica#388]
/usr/lib/tomcat/webapps/LibreClinica/ws/src/main/java/org/akaza/openclinica/ws/CrfEndpoint.java:24:33
java: package org.openclinica.ws.crf.v1 does not exist

package does not exist ? I am new to this can you guyz help ?

**Comment by toskrip** [comment]
I suppose, you are trying to build the system on your own?

You should check the developer documentation here:

https://libreclinica.org/documentation/development/docsify.html#/development/dev-machine

for development/build the java8 is still needed.
