### ISSUE TITLE
Audit User Activity: logouts are not displayed

### ISSUE THREAD

**Issue by GerbenRienk** [reliatec-gmbh/LibreClinica#40]
There seem to be no records for logout in table audit_user_login.

**Comment by GerbenRienk** [comment]
There seem to be no records for logout in table audit_user_login.

**Comment by chae-reliatec** [comment]
I can reproduce this issue with LC-0.2.0.

**Comment by chae-reliatec** [comment]
the logging of the user logout event is now reenabled
