### ISSUE TITLE
LibreClinica-odm: testing new module

### ISSUE THREAD

**Issue by toskrip** [reliatec-gmbh/LibreClinica#5]
**objective**
LibreClinica-odm is a library that contains object domain model for extended CDISC ODM data standard that is used within LibreClinica. This model has to correspond the XML representation of CDISC ODM data as it allows JAXB supported marshalling (object graph to XML) and unmarshalling (XML to object graph) operations. The actually model definition is captured within appropriate xsd scheme definition. The Java class representation of this domain model can be generated during the build process and there is no good reason for having to version control it or have the resulting model as jar library as external dependency. New project module (odm) is introduced for the purpose of bringing the scheme definitions to be internal part of the project. The build process should take care of creating the LibreClinica-odm jar using it within other project modules that depend on it.

**reason for change**
Streamline the build process and get rid of externally fetched non standard library dependency.

**workflow**
1. mvn clean install

**expected result when error free**
1. build creates target/LibreClinica-odm-major.minor.jar
2. build creates the rest of targets (LibreClinica-core-major.minor.patch.jar, LibreClinica-web-major.minor.patch.war, LibreClinica-ws-major.minor.patch.war)

**expected result when malfunctioning**
1. target/LibreClinica-odm-major.minor.jar missing
2. build of the rest of targets fails

Note:
groupId=org.libreclinica.odm
version=2.2

**Comment by toskrip** [comment]
changes will be organised in new branch (lc-odm)

**Comment by toskrip** [comment]
created pull request #60

**Comment by chae-reliatec** [comment]
I merged the code changes.
