### ISSUE TITLE
Person ID in Subject Matrix

### ISSUE THREAD

**Issue by toskrip** [reliatec-gmbh/LibreClinica#61]
**objective**
Subject Matrix view in LibreClinica allows for dynamic show/hide of extra Study Subject properties for tabular display. It is possible e.g. by clicking on Show More link to display additional Secondary ID property of Study Subject (not taking into account the Study configuration, if Secondary ID is not collected it will be empty). This view is especially usefull for powerusers as it also allows to setup additional filtering and sorting of Study Subjects based on these extra table columns.

**reason for change**
Person ID is currently not shown in Subject Matrix (although Subject details view displays it). The idea is to the display of Person ID on Show More click to allow users to apply filtering and sorting criteria for this property.

**workflow**

1. User login to LibreClinica
2. User navigates to Subject Matrix view to display the Study Subject table
3. User click on Show More to display additional Study Subject/Subject properties
4. User click on Hide to hide additional Study Subject/Subject properties

**expected result when error free**

on Show More
- Study without Subject Groups

1. Person ID column is shown as 7th element (after Secondary ID before Event Definitions) and Subject data is loaded
2. Person ID is sortable and filterable

- Study with Subject Groups

1. Person ID column is shown as 7th element (after Secondary ID before Subject Groups) and Subject data is loaded
2. Person ID is sortable and filterable

on Hide
- Study with or without Subject Groups

1. Only Study Subject ID column stays shown (followed by Event Definitions) all additional properties including Person ID (and Subject Groups if applicable) are hidden

**expected result when malfunctioning**

1. Show/Hide logic is not showing/hiding additional properties as expected
2. Person ID Subject data is not loading
3. Person ID is not filterable
4. Person ID is not sortable

**Comment by toskrip** [comment]
I have this implemented and tested for LibreClinica now because we need this feature (internally) however it is generic enough (IMHO useful for other as well) so if there is an interest I can create a pull request.

**Comment by GerbenRienk** [comment]
I'm definitely in favour and I will write a test scenario for it.

**Comment by toskrip** [comment]
created pull request #63
