### ISSUE TITLE
bugfix: discrepancy notes in groups get lost/overwritten in case of validation error

### ISSUE THREAD

**Issue by oba-reliatec** [reliatec-gmbh/LibreClinica#7]
**Preconditions**
- CRF named Gr01 with an item group containing field01 to field04

**Steps to reproduce**
1. Open CRF in edit mode
2. enter valid values for field01, field02, and field03 with a discrepancy note (dn) for each field and save
3. re-open CRF in edit mode
4. add a new line of the group, and enter valid values and dn for field01 and field02
5. enter an invalid value in field03 (e. g. string in an integer field) and save -> validation error message

**Error observed**
The dn from the first group line overwrite the dn in the second line.

**Comment by chae-reliatec** [comment]
The error is fixed and tested. The code is merged into lc-develop.
