### ISSUE TITLE
update lib "commons-fileupload:commons-fileupload"

### ISSUE THREAD

**Issue by chae-reliatec** [reliatec-gmbh/LibreClinica#9]
Update the library commons-fileupload:commons-fileupload from version 1.2 to 1.3.3. The most current version is 1.4 but it behaves different. It throws an error when an file is uploaded that already exist (same name). Therefore it is not possible to reupload a modified crf version.

**Comment by toskrip** [comment]
Just an observation which may be relevant to this issue. In data management a good practice is to include eCRF version numbers into the filename (that would prevent the problem). I actually think that what the older version of fileupload allows is a bug. When you upload eCRF into EDC to preview it before submit it goes to libreclinica.data/crf/original folder (applies for new eCRFs as well as for new version of eCRFs). There it is stored with its original filename. Only after submitting the previewed eCRF into database it creates a copy of the .xls that is placed into libreclinica.data/crf/new folder but here the filename is generated to be unique.

The old version of library overwrites the files with the same name in libreclinica.data/crf/original folder. Normally it is not an issue (those files are there only for the purpose of preview but what is also in this folder is the .xls template of blank eCRF. I recently had a case when datamanager was testing new study specific eCRF and did not change the name (kept the name of template .xls). And he wanted to just preview the form to check if it renders fine but the side effect was that he overwritten the default template silently and suddenly his new eCRF was stored on the server as template for anybody who wanted to download blank .xls.

In my opinion, throwing error is correct and users should be forced ro rename their eCRFs uniquely at least as long as the software behaves this way.

**Comment by chae-reliatec** [comment]
@toskrip 
I totally understand your arguments. 
We like to preserve the current behavior for the moment. Please feel free to create a note for this topic and we will discuss later and create an issue for it afterwards.
